name: Publish_Docker
on: [ push ]
jobs:
    build:
        runs-on: ubuntu-latest
        name: Build image job
        steps:
            - name: Checkout master
              uses: actions/checkout@master
            - name: Build and publish image
              timeout-minutes: 1200
              uses: ilteoood/docker_buildx@master
              with:
                publish: true
                imageName: jianhuayanyu/autoremove
                platform: linux/amd64,linux/arm64
                dockerUser: ${{ secrets.DOCKER_USERNAME }}
                dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
